.PHONY: all clean fclean l l_clean l_fclean l_re

all:
	make -f mac_make/Makefile

clean:
	make clean -f mac_make/Makefile

fclean:
	make fclean -f mac_make/Makefile

re:
	make re -f mac_make/Makefile

l:
	make -f linux_make/Makefile

l_clean:
	make clean -f linux_make/Makefile

l_fclean:
	make fclean -f linux_make/Makefile

l_re:
	make re -f linux_make/Makefile
