.PHONY: all clean fclean l l_clean l_fclean l_re

all:
	make -f mac_make/Makefile -s

clean:
	make clean -f mac_make/Makefile -s

fclean:
	make fclean -f mac_make/Makefile -s

re:
	make re -f mac_make/Makefile -s

l:
	make -f linux_make/Makefile -s

l_clean:
	make clean -f linux_make/Makefile -s

l_fclean:
	make fclean -f linux_make/Makefile -s

l_re:
	make re -f linux_make/Makefile -s
